package wisc.virgil.virgil;

import android.database.sqlite.SQLiteDatabase;

import java.io.Serializable;
import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import wisc.virgil.virgil.FavoriteMuseum;

import wisc.virgil.virgil.FavoriteMuseumDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession implements Serializable {

    private final DaoConfig favoriteMuseumDaoConfig;

    private final FavoriteMuseumDao favoriteMuseumDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        favoriteMuseumDaoConfig = daoConfigMap.get(FavoriteMuseumDao.class).clone();
        favoriteMuseumDaoConfig.initIdentityScope(type);

        favoriteMuseumDao = new FavoriteMuseumDao(favoriteMuseumDaoConfig, this);

        registerDao(FavoriteMuseum.class, favoriteMuseumDao);
    }
    
    public void clear() {
        favoriteMuseumDaoConfig.getIdentityScope().clear();
    }

    public FavoriteMuseumDao getFavoriteMuseumDao() {
        return favoriteMuseumDao;
    }

}
