package wisc.virgil.virgil;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FAVORITE_MUSEUM.
 */
public class FavoriteMuseum {

    private Long id;
    private Integer museumID;
    private String name;
    private String address;
    private String pathToPicture;
    private Boolean display;

    public FavoriteMuseum() {
    }

    public FavoriteMuseum(Long id) {
        this.id = id;
    }

    public FavoriteMuseum(Long id, Integer museumID, String name, String address, String pathToPicture, Boolean display) {
        this.id = id;
        this.museumID = museumID;
        this.name = name;
        this.address = address;
        this.pathToPicture = pathToPicture;
        this.display = display;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getMuseumID() {
        return museumID;
    }

    public void setMuseumID(Integer museumID) {
        this.museumID = museumID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPathToPicture() {
        return pathToPicture;
    }

    public void setPathToPicture(String pathToPicture) {
        this.pathToPicture = pathToPicture;
    }

    public Boolean getDisplay() {
        return display;
    }

    public void setDisplay(Boolean display) {
        this.display = display;
    }

}
